create table task(
	id serial primary key,
	name varchar,
	age int,
	gender varchar,
	country varchar,
	income int
)
select * from task
insert into task values(1,'anurag',22,'m','india',3.5)
insert into task values(2,'shrey',26,'m','india',6)
insert into task(name,age,gender,country,income) values('leon',23,'m','india',4)
insert into task(name,age,gender,country,income) values('reyna',19,'f','usa',9)
insert into task(name,age,gender,country,income) values('chamber',26,'m','arab',10)
insert into task(name,age,gender,country,income) values('deadlock',20,'f','kenya',21)
insert into task(name,age,gender,country,income) values('killjoy',18,'f','brazil',5)
insert into task(name,age,gender,country,income) values('ghost',23,'m','pakistan',6)
insert into task(name,age,gender,country,income) values('Raquel Branch',25,'m','russia',3)
insert into task(name,age,gender,country,income) values('Aila Moses',21,'f','india',6)
insert into task(name,age,gender,country,income) values('Adalyn English',32,'f','india',14)
insert into task(name,age,gender,country,income) values('Frances Beil',24,'m','russia',12)
insert into task(name,age,gender,country,income) values('Ashlyn Paul',25,'m','uk',4)
insert into task(name,age,gender,country,income) values('Denise Corona',26,'f','india',4)
insert into task(name,age,gender,country,income) values('Scarlett Baker',22,'m','uk',6)
insert into task(name,age,gender,country,income) values('Maxine Atkinson',21,'m','indian',7)
insert into task(name,age,gender,country,income) values('Rachel Juarez',35,'f','russia',4)
insert into task(name,age,gender,country,income) values('Keira Madden',26,'m','uk',15)
insert into task(name,age,gender,country,income) values('Valeria Harding',31,'m','pakistan',23)
insert into task(name,age,gender,country,income) values('Kendra Leach',42,'f','australia',15)
insert into task(name,age,gender,country,income) values('Ivory',23,'m','us',21)
insert into task(name,age,gender,country,income) values('Oaklee',26,'f','uk',5)
insert into task(name,age,gender,country,income) values('Ruth',23,'m','pakistan',4)
insert into task(name,age,gender,country,income) values('Aniya',28,'f','nepal',41)
insert into task(name,age,gender,country,income) values('Evangeline',28,'m','india',22)
insert into task(name,age,gender,country,income) values('Lauren',27,'f','pakistan',12)
insert into task(name,age,gender,country,income) values('Jaylin',23,'m','russia',21)
insert into task(name,age,gender,country,income) values('Zoe',22,'m','india',4)
insert into task(name,age,gender,country,income) values('Maeve',23,'f','indonasia',9)
insert into task(name,age,gender,country,income) values('Murphy',28,'m','japan',6)
insert into task(name,age,gender,country,income) values('Emerie',22,'f','china',7)
insert into task(name,age,gender,country,income) values('Mariah',27,'m','india',3)
insert into task(name,age,gender,country,income) values('Makenzie',22,'m','pakistan',5)
insert into task(name,age,gender,country,income) values('Lillian',32,'f','china',7)
insert into task(name,age,gender,country,income) values('Mariana',27,'m','indonasia',6)
insert into task(name,age,gender,country,income) values('Allyson',28,'m','india',1)
insert into task(name,age,gender,country,income) values('Anya',20,'m','pakistan',6)
insert into task(name,age,gender,country,income) values('Julie',22,'f','russia',3)
insert into task(name,age,gender,country,income) values('ghPhoebeost',21,'m','china',7)
insert into task(name,age,gender,country,income) values('Skylar',25,'f','india',8)
insert into task(name,age,gender,country,income) values('Macy',26,'m','china',3)
insert into task(name,age,gender,country,income) values('Rudy',21,'m','pakistan',12)
insert into task(name,age,gender,country,income) values('Boone',21,'f','russia',24)
insert into task(name,age,gender,country,income) values('Scott',27,'m','india',7)
insert into task(name,age,gender,country,income) values('Rudy',28,'m','pakistan',1)
insert into task(name,age,gender,country,income) values('Kabir',23,'f','russia',7)
insert into task(name,age,gender,country,income) values('Eliezer',22,'f','india',78)